version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx-conf:/etc/nginx
    depends_on:
      example-frontend:
        condition: service_started
      example-backend:
        condition: service_started
  example-frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api/
    depends_on:
      - example-backend
  example-backend:
    image: example-backend-v2
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_started
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7.4.1-alpine
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db_backend
    volumes:
      - ./database:/var/lib/postgresql/data
