version: "3.8"

services:
  example-frontend:
    image: example-frontend-v2
    ports:
      - 127.0.0.1:5000:5000
    container_name: example-frontend
  example-backend:
    image: example-backend-v2
    ports:
      - 127.0.0.1:8080:8080
    container_name: example-backend
