version: "3.8"

services:
  example-frontend:
    image: example-frontend-v2
    depends_on:
      - example-backend
    ports:
      - 5000:5000
  example-backend:
    image: example-backend-v2
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_started
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
    ports:
      - 8080:8080
  redis:
    image: redis:7.4.1-alpine
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db_backend
    volumes:
      - db_backend_volume:/var/lib/postgresql/data

volumes:
  db_backend_volume:
